=== anchore/grype/grype/db/internal/provider/unmarshal/osvmodel/schema-v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/ossf/osv-schema/main/validation/schema.json",
  "title": "Open Source Vulnerability",
  "description": "A schema for describing a vulnerability in an open source package. See also https://ossf.github.io/osv-schema/",
  "type": "object",
  "properties": {
    "schema_version": {
      "type": "string"
    },
    "id": {
      "$ref": "#/$defs/prefix"
    },
    "modified": {
      "$ref": "#/$defs/timestamp"
    },
    "published": {
      "$ref": "#/$defs/timestamp"
    },
    "withdrawn": {
      "$ref": "#/$defs/timestamp"
    },
    "aliases": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string"
      }
    },
    "related": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "upstream": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "summary": {
      "type": "string"
    },
    "details": {
      "type": "string"
    },
    "severity": {
      "$ref": "#/$defs/severity"
    },
    "affected": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "package": {
            "type": "object",
            "properties": {
              "ecosystem": {
                "$ref": "#/$defs/ecosystemWithSuffix"
              },
              "name": {
                "type": "string"
              },
              "purl": {
                "type": "string"
              }
            },
            "required": [
              "ecosystem",
              "name"
            ]
          },
          "severity": {
            "$ref": "#/$defs/severity"
          },
          "ranges": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "GIT",
                    "SEMVER",
                    "ECOSYSTEM"
                  ]
                },
                "repo": {
                  "type": "string"
                },
                "events": {
                  "title": "events must contain an introduced object and may contain fixed, last_affected or limit objects",
                  "type": "array",
                  "contains": {
                    "required": [
                      "introduced"
                    ]
                  },
                  "items": {
                    "type": "object",
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "introduced": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "introduced"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "fixed": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "fixed"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "last_affected": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "last_affected"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "limit": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "limit"
                        ]
                      }
                    ]
                  },
                  "minItems": 1
                },
                "database_specific": {
                  "type": "object"
                }
              },
              "allOf": [
                {
                  "title": "GIT ranges require a repo",
                  "if": {
                    "properties": {
                      "type": {
                        "const": "GIT"
                      }
                    }
                  },
                  "then": {
                    "required": [
                      "repo"
                    ]
                  }
                },
                {
                  "title": "GIT ranges must use full-length commit hashes",
                  "if": {
                    "properties": {
                      "type": {
                        "const": "GIT"
                      }
                    }
                  },
                  "then": {
                    "properties": {
                      "events": {
                        "items": {
                          "oneOf": [
                            {
                              "type": "object",
                              "properties": {
                                "introduced": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "introduced"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "fixed": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "fixed"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "last_affected": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "last_affected"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "limit": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "limit"
                              ]
                            }
                          ]
                        }
                      }
                    }
                  }
                },
                {
                  "title": "last_affected and fixed events are mutually exclusive",
                  "if": {
                    "properties": {
                      "events": {
                        "contains": {
                          "required": [
                            "last_affected"
                          ]
                        }
                      }
                    }
                  },
                  "then": {
                    "not": {
                      "properties": {
                        "events": {
                          "contains": {
                            "required": [
                              "fixed"
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              ],
              "required": [
                "type",
                "events"
              ]
            }
          },
          "versions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "ecosystem_specific": {
            "type": "object"
          },
          "database_specific": {
            "type": "object"
          }
        }
      }
    },
    "references": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ADVISORY",
              "ARTICLE",
              "DETECTION",
              "DISCUSSION",
              "REPORT",
              "FIX",
              "INTRODUCED",
              "GIT",
              "PACKAGE",
              "EVIDENCE",
              "WEB"
            ]
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "type",
          "url"
        ]
      }
    },
    "credits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "contact": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "type": {
            "type": "string",
            "enum": [
              "FINDER",
              "REPORTER",
              "ANALYST",
              "COORDINATOR",
              "REMEDIATION_DEVELOPER",
              "REMEDIATION_REVIEWER",
              "REMEDIATION_VERIFIER",
              "TOOL",
              "SPONSOR",
              "OTHER"
            ]
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "database_specific": {
      "type": "object"
    }
  },
  "required": [
    "id",
    "modified"
  ],
  "allOf": [
    {
      "if": {
        "required": [
          "severity"
        ]
      },
      "then": {
        "properties": {
          "affected": {
            "items": {
              "properties": {
                "severity": {
                  "type": "null"
                }
              }
            }
          }
        }
      }
    }
  ],
  "$defs": {
    "ecosystemName": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "enum": [
        "AlmaLinux",
        "Alpaquita",
        "Alpine",
        "Android",
        "Azure Linux",
        "BellSoft Hardened Containers",
        "Bioconductor",
        "Bitnami",
        "Chainguard",
        "CleanStart",
        "ConanCenter",
        "CRAN",
        "crates.io",
        "Debian",
        "Docker Hardened Images",
        "Echo",
        "FreeBSD",
        "GHC",
        "GitHub Actions",
        "Go",
        "Hackage",
        "Hex",
        "Homebrew",
        "Julia",
        "Kubernetes",
        "Linux",
        "Mageia",
        "Maven",
        "MinimOS",
        "npm",
        "NuGet",
        "opam",
        "openEuler",
        "openSUSE",
        "OSS-Fuzz",
        "Packagist",
        "Photon OS",
        "Pub",
        "PyPI",
        "Red Hat",
        "Red Hat Lightwell",
        "Rocky Linux",
        "Root",
        "RubyGems",
        "SUSE",
        "SwiftURL",
        "TuxCare",
        "Ubuntu",
        "vcpkg",
        "VSCode",
        "Wolfi",
        "WordPress"
      ]
    },
    "ecosystemSuffix": {
      "type": "string",
      "pattern": ":.+"
    },
    "ecosystemWithSuffix": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "pattern": "^(AlmaLinux|Alpaquita|Alpine|Android|Azure Linux|BellSoft Hardened Containers|Bioconductor|Bitnami|Chainguard|CleanStart|ConanCenter|CRAN|crates\\.io|Debian|Docker Hardened Images|Echo|FreeBSD|GHC|GitHub Actions|Go|Hackage|Hex|Homebrew|Julia|Kubernetes|Linux|Mageia|Maven|MinimOS|npm|NuGet|opam|openEuler|openSUSE|OSS-Fuzz|Packagist|Photon OS|Pub|PyPI|Red Hat|Red Hat Lightwell|Rocky Linux|Root|RubyGems|SUSE|SwiftURL|TuxCare|Ubuntu|vcpkg|VSCode|Wolfi|WordPress|GIT)(:.+)?$"
    },
    "prefix": {
      "type": "string",
      "title": "Currently supported home database identifier prefixes",
      "description": "These home databases are also documented at https://ossf.github.io/osv-schema/#id-modified-fields",
      "pattern": "^(x_|(ASB-A|PUB-A|ALPINE|ALSA|ALBA|ALEA|AZL|BELL|BIT|BREW|CGA|CLEANSTART|CLSA|CURL|CVE|DEBIAN|DHI|DRUPAL|DSA|DLA|ELA|DTSA|ECHO|EEF|FreeBSD|GHSA|GO|GSD|HSEC|JLSEC|KUBE|LBSEC|LSN|MAL|MINI|MGASA|OESA|OSEC|OSV|openSUSE-SU|PHSA|PSF|PYSEC|RHBA|RHEA|RHLW|RHSA|RLSA|RXSA|RSEC|ROOT|RUSTSEC|SUSE-[SRFO]U|UBUNTU|USN|V8|VCPKG)-)"
    },
    "severity": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "CVSS_V2",
              "CVSS_V3",
              "CVSS_V4",
              "Ubuntu"
            ]
          },
          "score": {
            "type": "string"
          },
          "source": {
            "type": "string",
            "enum": [
              "NVD",
              "CNA",
              "SELF"
            ]
          }
        },
        "allOf": [
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V2"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^((AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))/)*(AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V3"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:3[.][01]/((AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*(AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V4"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:4[.]0/AV:[NALP]/AC:[LH]/AT:[NP]/PR:[NLH]/UI:[NPA]/VC:[HLN]/VI:[HLN]/VA:[HLN]/SC:[HLN]/SI:[HLN]/SA:[HLN](/E:[XAPU])?(/CR:[XHML])?(/IR:[XHML])?(/AR:[XHML])?(/MAV:[XNALP])?(/MAC:[XLH])?(/MAT:[XNP])?(/MPR:[XNLH])?(/MUI:[XNPA])?(/MVC:[XNLH])?(/MVI:[XNLH])?(/MVA:[XNLH])?(/MSC:[XNLH])?(/MSI:[XNLHS])?(/MSA:[XNLHS])?(/S:[XNP])?(/AU:[XNY])?(/R:[XAUI])?(/V:[XDC])?(/RE:[XLMH])?(/U:(X|Clear|Green|Amber|Red))?$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "Ubuntu"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "enum": [
                    "negligible",
                    "low",
                    "medium",
                    "high",
                    "critical"
                  ]
                }
              }
            }
          }
        ],
        "required": [
          "type",
          "score"
        ]
      }
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z"
    }
  },
  "additionalProperties": false
}

=== anchore/grype/grype/db/v6/build/transformers/osv/testdata/GO-2024-2826.json
{
  "schema_version": "1.3.1",
  "id": "GO-2024-2826",
  "modified": "2024-07-09T19:33:56Z",
  "published": "2024-05-10T20:07:17Z",
  "aliases": [
    "CVE-2024-32886",
    "GHSA-649x-hxfx-57j2"
  ],
  "summary": "Denial of service attack by triggering unbounded memory usage in vitess.io/vitess",
  "details": "When executing a query, the vtgate will go into an endless loop that also keeps consuming memory and eventually will OOM. This causes a denial of service.",
  "affected": [
    {
      "package": {
        "name": "vitess.io/vitess",
        "ecosystem": "Go"
      },
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.17.7"
            },
            {
              "introduced": "0.18.0"
            },
            {
              "fixed": "0.18.5"
            },
            {
              "introduced": "0.19.0"
            },
            {
              "fixed": "0.19.4"
            }
          ]
        }
      ],
      "ecosystem_specific": {
        "imports": [
          {
            "path": "vitess.io/vitess/go/mysql/collations/charset",
            "symbols": [
              "Convert",
              "ConvertFromBinary",
              "ConvertFromUTF8",
              "Validate",
              "convertSlow"
            ]
          },
          {
            "path": "vitess.io/vitess/go/mysql/collations/charset/unicode",
            "symbols": [
              "Charset_ucs2.DecodeRune",
              "Charset_utf16be.DecodeRune",
              "Charset_utf16be.EncodeRune",
              "Charset_utf32.EncodeRune"
            ]
          },
          {
            "path": "vitess.io/vitess/go/vt/vtgate/evalengine",
            "symbols": [
              "Add",
              "AggregateEvalTypes",
              "CoerceTo",
              "CoerceTypes",
              "Column.Format",
              "Column.FormatFast",
              "Comparison.ApplyTinyWeights",
              "Comparison.Compare",
              "Comparison.Less",
              "Comparison.More",
              "Comparison.Sort",
              "Comparison.SortResult",
              "CompiledExpr.Format",
              "CompiledExpr.FormatFast",
              "Divide",
              "EvalResult.MustBoolean",
              "EvalResult.String",
              "EvalResult.ToBoolean",
              "EvalResult.ToBooleanStrict",
              "EvalResult.TupleValues",
              "EvalResult.Value",
              "ExpressionEnv.Evaluate",
              "ExpressionEnv.EvaluateVM",
              "FieldResolver.Column",
              "IntroducerExpr.eval",
              "Literal.Format",
              "Literal.FormatFast",
              "Merger.Init",
              "Merger.Pop",
              "Merger.Push",
              "Multiply",
              "NewLiteralBinaryFromBit",
              "NewLiteralDateFromBytes",
              "NewLiteralDatetimeFromBytes",
              "NewLiteralDecimalFromBytes",
              "NewLiteralFloatFromBytes",
              "NewLiteralIntegralFromBytes",
              "NewLiteralTimeFromBytes",
              "NullSafeAdd",
              "NullsafeCompare",
              "NullsafeHashcode",
              "NullsafeHashcode128",
              "OrderByParams.Compare",
              "OrderByParams.String",
              "Sorter.Push",
              "Sorter.Sorted",
              "Subtract",
              "Translate",
              "TupleBindVariable.Format",
              "TupleBindVariable.FormatFast",
              "TupleExpr.Format",
              "TupleExpr.FormatFast",
              "UnsupportedCollationError.Error",
              "UntypedExpr.Compile",
              "UntypedExpr.Format",
              "UntypedExpr.FormatFast",
              "WeightString",
              "aggregationDecimal.Add",
              "aggregationDecimal.Max",
              "aggregationDecimal.Min",
              "aggregationFloat.Add",
              "aggregationFloat.Max",
              "aggregationFloat.Min",
              "aggregationInt.Add",
              "aggregationInt.Max",
              "aggregationInt.Min",
              "aggregationMinMax.Max",
              "aggregationMinMax.Min",
              "aggregationSumAny.Add",
              "aggregationSumCount.Add",
              "aggregationUint.Add",
              "aggregationUint.Max",
              "aggregationUint.Min",
              "argError.Error",
              "assembler.Fn_JSON_KEYS",
              "assembler.Fn_REGEXP_REPLACE_slow",
              "assembler.PushLiteral",
              "astCompiler.translateIntroducerExpr",
              "errJSONType.Error",
              "evalBytes.Hash"
            ]
          }
        ],
        "custom_ranges": [
          {
            "type": "ECOSYSTEM",
            "events": [
              {
                "introduced": "0"
              },
              {
                "fixed": "17.0.7"
              },
              {
                "introduced": "18.0.0"
              },
              {
                "fixed": "18.0.5"
              },
              {
                "introduced": "19.0.0"
              },
              {
                "fixed": "19.0.4"
              }
            ]
          }
        ]
      }
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://github.com/vitessio/vitess/security/advisories/GHSA-649x-hxfx-57j2"
    },
    {
      "type": "FIX",
      "url": "https://github.com/vitessio/vitess/commit/2fd5ba1dbf6e9b32fdfdaf869d130066b1b5c0df"
    },
    {
      "type": "FIX",
      "url": "https://github.com/vitessio/vitess/commit/9df4b66550e46b5d7079e21ed0e1b0f49f92b055"
    },
    {
      "type": "FIX",
      "url": "https://github.com/vitessio/vitess/commit/c46dc5b6a4329a10589ca928392218d96031ac8d"
    },
    {
      "type": "FIX",
      "url": "https://github.com/vitessio/vitess/commit/d438adf7e34a6cf00fe441db80842ec669a99202"
    },
    {
      "type": "WEB",
      "url": "https://github.com/vitessio/vitess/blob/8f6cfaaa643a08dc111395a75a2d250ee746cfa8/go/mysql/collations/charset/convert.go#L73-L79"
    },
    {
      "type": "WEB",
      "url": "https://github.com/vitessio/vitess/blob/8f6cfaaa643a08dc111395a75a2d250ee746cfa8/go/mysql/collations/charset/unicode/utf16.go#L69-L71"
    }
  ],
  "credits": [
    {
      "name": "@dbussink, @mattrobenolt, and @vmg"
    }
  ],
  "database_specific": {
    "url": "https://pkg.go.dev/vuln/GO-2024-2826",
    "review_status": "REVIEWED"
  }
}

=== anchore/grype/grype/db/v6/build/transformers/osv/testdata/GO-2022-0969.json
{
  "affected": [
    {
      "ecosystem_specific": {
        "imports": [
          {
            "path": "net/http",
            "symbols": [
              "ListenAndServe",
              "ListenAndServeTLS",
              "Serve",
              "ServeTLS",
              "Server.ListenAndServe",
              "Server.ListenAndServeTLS",
              "Server.Serve",
              "Server.ServeTLS",
              "http2Server.ServeConn",
              "http2serverConn.goAway"
            ]
          }
        ]
      },
      "package": {
        "ecosystem": "Go",
        "name": "stdlib"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1.18.6"
            },
            {
              "introduced": "1.19.0-0"
            },
            {
              "fixed": "1.19.1"
            }
          ],
          "type": "SEMVER"
        }
      ]
    },
    {
      "ecosystem_specific": {
        "imports": [
          {
            "path": "golang.org/x/net/http2",
            "symbols": [
              "Server.ServeConn",
              "serverConn.goAway"
            ]
          }
        ]
      },
      "package": {
        "ecosystem": "Go",
        "name": "golang.org/x/net"
      },
      "ranges": [
        {
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "0.0.0-20220906165146-f3363e06e74c"
            }
          ],
          "type": "SEMVER"
        }
      ]
    }
  ],
  "aliases": [
    "CVE-2022-27664",
    "GHSA-69cg-p879-7622"
  ],
  "credits": [
    {
      "name": "Bahruz Jabiyev"
    },
    {
      "name": "Tommaso Innocenti"
    },
    {
      "name": "Anthony Gavazzi"
    },
    {
      "name": "Steven Sprecher"
    },
    {
      "name": "Kaan Onarlioglu"
    }
  ],
  "database_specific": {
    "review_status": "REVIEWED",
    "url": "https://pkg.go.dev/vuln/GO-2022-0969"
  },
  "details": "HTTP/2 server connections can hang forever waiting for a clean shutdown that was preempted by a fatal error. This condition can be exploited by a malicious client to cause a denial of service.",
  "id": "GO-2022-0969",
  "modified": "2024-05-20T16:03:47Z",
  "published": "2022-09-12T20:23:06Z",
  "references": [
    {
      "type": "WEB",
      "url": "https://groups.google.com/g/golang-announce/c/x49AQzIVX-s"
    },
    {
      "type": "REPORT",
      "url": "https://go.dev/issue/54658"
    },
    {
      "type": "FIX",
      "url": "https://go.dev/cl/428735"
    }
  ],
  "schema_version": "1.3.1",
  "summary": "Denial of service in net/http and golang.org/x/net/http2"
}

=== anchore/grype/grype/db/v6/build/transformers/osv/test-fixtures/ALSA-2025-7467.json
{
  "id": "ALSA-2025:7467",
  "summary": "Moderate: skopeo security update",
  "aliases": [
    "CVE-2025-27144"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "AlmaLinux:10",
        "name": "skopeo"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:1.18.1-1.el10_0"
            }
          ]
        }
      ]
    },
    {
      "package": {
        "ecosystem": "AlmaLinux:10",
        "name": "skopeo-tests"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2:1.18.1-1.el10_0"
            }
          ]
        }
      ]
    }
  ],
  "published": "2025-05-13T00:00:00Z",
  "modified": "2025-07-02T12:50:06Z",
  "details": "The skopeo command lets you inspect images from container image registries.",
  "references": [
    {
      "url": "https://errata.almalinux.org/10/ALSA-2025-7467.html",
      "type": "ADVISORY"
    }
  ],
  "database_specific": {
    "anchore": {
      "record_type": "advisory"
    }
  }
}

=== anchore/grype/grype/db/v6/build/transformers/osv/test-fixtures/BIT-node-2020-8201.json
{
  "schema_version": "1.5.0",
  "id": "BIT-node-2020-8201",
  "details": "Node.js < 12.18.4 and < 14.11 can be exploited to perform HTTP desync attacks and deliver malicious payloads to unsuspecting users. The payloads can be crafted by an attacker to hijack user sessions, poison cookies, perform clickjacking, and a multitude of other attacks depending on the architecture of the underlying system. The attack was possible due to a bug in processing of carrier-return symbols in the HTTP header names.",
  "aliases": [
    "CVE-2020-8201"
  ],
  "affected": [
    {
      "package": {
        "ecosystem": "Bitnami",
        "name": "node",
        "purl": "pkg:bitnami/node"
      },
      "severity": [
        {
          "type": "CVSS_V3",
          "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N"
        }
      ],
      "ranges": [
        {
          "type": "SEMVER",
          "events": [
            {
              "introduced": "12.0.0"
            },
            {
              "fixed": "12.18.4"
            },
            {
              "introduced": "14.0.0"
            },
            {
              "fixed": "14.11.0"
            }
          ],
          "database_specific": {
            "anchore": {
              "fixes": [
                {
                  "version": "12.18.4",
                  "date": "2020-09-15",
                  "kind": "first-observed"
                },
                {
                  "version": "14.11.0",
                  "date": "2020-09-15",
                  "kind": "first-observed"
                }
              ]
            }
          }
        }
      ]
    }
  ],
  "database_specific": {
    "severity": "High",
    "cpes": [
      "cpe:2.3:a:nodejs:node.js:*:*:*:*:*:*:*:*",
      "cpe:2.3:a:nodejs:node.js:*:*:*:*:lts:*:*:*"
    ]
  },
  "references": [
    {
      "type": "WEB",
      "url": "https://nodejs.org/en/blog/vulnerability/september-2020-security-releases/"
    },
    {
      "type": "WEB",
      "url": "https://security.gentoo.org/glsa/202101-07"
    }
  ],
  "published": "2024-03-06T11:08:09.371Z",
  "modified": "2024-03-06T11:25:28.861Z"
}
