=== anchore/grype/grype/db/internal/provider/unmarshal/osvmodel/schema-v1.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/ossf/osv-schema/main/validation/schema.json",
  "title": "Open Source Vulnerability",
  "description": "A schema for describing a vulnerability in an open source package. See also https://ossf.github.io/osv-schema/",
  "type": "object",
  "properties": {
    "schema_version": {
      "type": "string"
    },
    "id": {
      "$ref": "#/$defs/prefix"
    },
    "modified": {
      "$ref": "#/$defs/timestamp"
    },
    "published": {
      "$ref": "#/$defs/timestamp"
    },
    "withdrawn": {
      "$ref": "#/$defs/timestamp"
    },
    "aliases": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "string"
      }
    },
    "related": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "upstream": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "summary": {
      "type": "string"
    },
    "details": {
      "type": "string"
    },
    "severity": {
      "$ref": "#/$defs/severity"
    },
    "affected": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "package": {
            "type": "object",
            "properties": {
              "ecosystem": {
                "$ref": "#/$defs/ecosystemWithSuffix"
              },
              "name": {
                "type": "string"
              },
              "purl": {
                "type": "string"
              }
            },
            "required": [
              "ecosystem",
              "name"
            ]
          },
          "severity": {
            "$ref": "#/$defs/severity"
          },
          "ranges": {
            "type": "array",
            "items": {
              "type": "object",
              "properties": {
                "type": {
                  "type": "string",
                  "enum": [
                    "GIT",
                    "SEMVER",
                    "ECOSYSTEM"
                  ]
                },
                "repo": {
                  "type": "string"
                },
                "events": {
                  "title": "events must contain an introduced object and may contain fixed, last_affected or limit objects",
                  "type": "array",
                  "contains": {
                    "required": [
                      "introduced"
                    ]
                  },
                  "items": {
                    "type": "object",
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "introduced": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "introduced"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "fixed": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "fixed"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "last_affected": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "last_affected"
                        ]
                      },
                      {
                        "type": "object",
                        "properties": {
                          "limit": {
                            "type": "string"
                          }
                        },
                        "required": [
                          "limit"
                        ]
                      }
                    ]
                  },
                  "minItems": 1
                },
                "database_specific": {
                  "type": "object"
                }
              },
              "allOf": [
                {
                  "title": "GIT ranges require a repo",
                  "if": {
                    "properties": {
                      "type": {
                        "const": "GIT"
                      }
                    }
                  },
                  "then": {
                    "required": [
                      "repo"
                    ]
                  }
                },
                {
                  "title": "GIT ranges must use full-length commit hashes",
                  "if": {
                    "properties": {
                      "type": {
                        "const": "GIT"
                      }
                    }
                  },
                  "then": {
                    "properties": {
                      "events": {
                        "items": {
                          "oneOf": [
                            {
                              "type": "object",
                              "properties": {
                                "introduced": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "introduced"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "fixed": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "fixed"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "last_affected": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "last_affected"
                              ]
                            },
                            {
                              "type": "object",
                              "properties": {
                                "limit": {
                                  "type": "string",
                                  "pattern": "^(0|[a-f0-9]{40}|[a-f0-9]{64})$"
                                }
                              },
                              "required": [
                                "limit"
                              ]
                            }
                          ]
                        }
                      }
                    }
                  }
                },
                {
                  "title": "last_affected and fixed events are mutually exclusive",
                  "if": {
                    "properties": {
                      "events": {
                        "contains": {
                          "required": [
                            "last_affected"
                          ]
                        }
                      }
                    }
                  },
                  "then": {
                    "not": {
                      "properties": {
                        "events": {
                          "contains": {
                            "required": [
                              "fixed"
                            ]
                          }
                        }
                      }
                    }
                  }
                }
              ],
              "required": [
                "type",
                "events"
              ]
            }
          },
          "versions": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "ecosystem_specific": {
            "type": "object"
          },
          "database_specific": {
            "type": "object"
          }
        }
      }
    },
    "references": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "ADVISORY",
              "ARTICLE",
              "DETECTION",
              "DISCUSSION",
              "REPORT",
              "FIX",
              "INTRODUCED",
              "GIT",
              "PACKAGE",
              "EVIDENCE",
              "WEB"
            ]
          },
          "url": {
            "type": "string",
            "format": "uri"
          }
        },
        "required": [
          "type",
          "url"
        ]
      }
    },
    "credits": {
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "type": "string"
          },
          "contact": {
            "type": "array",
            "items": {
              "type": "string"
            }
          },
          "type": {
            "type": "string",
            "enum": [
              "FINDER",
              "REPORTER",
              "ANALYST",
              "COORDINATOR",
              "REMEDIATION_DEVELOPER",
              "REMEDIATION_REVIEWER",
              "REMEDIATION_VERIFIER",
              "TOOL",
              "SPONSOR",
              "OTHER"
            ]
          }
        },
        "required": [
          "name"
        ]
      }
    },
    "database_specific": {
      "type": "object"
    }
  },
  "required": [
    "id",
    "modified"
  ],
  "allOf": [
    {
      "if": {
        "required": [
          "severity"
        ]
      },
      "then": {
        "properties": {
          "affected": {
            "items": {
              "properties": {
                "severity": {
                  "type": "null"
                }
              }
            }
          }
        }
      }
    }
  ],
  "$defs": {
    "ecosystemName": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "enum": [
        "AlmaLinux",
        "Alpaquita",
        "Alpine",
        "Android",
        "Azure Linux",
        "BellSoft Hardened Containers",
        "Bioconductor",
        "Bitnami",
        "Chainguard",
        "CleanStart",
        "ConanCenter",
        "CRAN",
        "crates.io",
        "Debian",
        "Docker Hardened Images",
        "Echo",
        "FreeBSD",
        "GHC",
        "GitHub Actions",
        "Go",
        "Hackage",
        "Hex",
        "Homebrew",
        "Julia",
        "Kubernetes",
        "Linux",
        "Mageia",
        "Maven",
        "MinimOS",
        "npm",
        "NuGet",
        "opam",
        "openEuler",
        "openSUSE",
        "OSS-Fuzz",
        "Packagist",
        "Photon OS",
        "Pub",
        "PyPI",
        "Red Hat",
        "Red Hat Lightwell",
        "Rocky Linux",
        "Root",
        "RubyGems",
        "SUSE",
        "SwiftURL",
        "TuxCare",
        "Ubuntu",
        "vcpkg",
        "VSCode",
        "Wolfi",
        "WordPress"
      ]
    },
    "ecosystemSuffix": {
      "type": "string",
      "pattern": ":.+"
    },
    "ecosystemWithSuffix": {
      "type": "string",
      "title": "Currently supported ecosystems",
      "description": "These ecosystems are also documented at https://ossf.github.io/osv-schema/#affectedpackage-field",
      "pattern": "^(AlmaLinux|Alpaquita|Alpine|Android|Azure Linux|BellSoft Hardened Containers|Bioconductor|Bitnami|Chainguard|CleanStart|ConanCenter|CRAN|crates\\.io|Debian|Docker Hardened Images|Echo|FreeBSD|GHC|GitHub Actions|Go|Hackage|Hex|Homebrew|Julia|Kubernetes|Linux|Mageia|Maven|MinimOS|npm|NuGet|opam|openEuler|openSUSE|OSS-Fuzz|Packagist|Photon OS|Pub|PyPI|Red Hat|Red Hat Lightwell|Rocky Linux|Root|RubyGems|SUSE|SwiftURL|TuxCare|Ubuntu|vcpkg|VSCode|Wolfi|WordPress|GIT)(:.+)?$"
    },
    "prefix": {
      "type": "string",
      "title": "Currently supported home database identifier prefixes",
      "description": "These home databases are also documented at https://ossf.github.io/osv-schema/#id-modified-fields",
      "pattern": "^(x_|(ASB-A|PUB-A|ALPINE|ALSA|ALBA|ALEA|AZL|BELL|BIT|BREW|CGA|CLEANSTART|CLSA|CURL|CVE|DEBIAN|DHI|DRUPAL|DSA|DLA|ELA|DTSA|ECHO|EEF|FreeBSD|GHSA|GO|GSD|HSEC|JLSEC|KUBE|LBSEC|LSN|MAL|MINI|MGASA|OESA|OSEC|OSV|openSUSE-SU|PHSA|PSF|PYSEC|RHBA|RHEA|RHLW|RHSA|RLSA|RXSA|RSEC|ROOT|RUSTSEC|SUSE-[SRFO]U|UBUNTU|USN|V8|VCPKG)-)"
    },
    "severity": {
      "type": [
        "array",
        "null"
      ],
      "items": {
        "type": "object",
        "properties": {
          "type": {
            "type": "string",
            "enum": [
              "CVSS_V2",
              "CVSS_V3",
              "CVSS_V4",
              "Ubuntu"
            ]
          },
          "score": {
            "type": "string"
          },
          "source": {
            "type": "string",
            "enum": [
              "NVD",
              "CNA",
              "SELF"
            ]
          }
        },
        "allOf": [
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V2"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^((AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))/)*(AV:[NAL]|AC:[LMH]|Au:[MSN]|[CIA]:[NPC]|E:(U|POC|F|H|ND)|RL:(OF|TF|W|U|ND)|RC:(UC|UR|C|ND)|CDP:(N|L|LM|MH|H|ND)|TD:(N|L|M|H|ND)|[CIA]R:(L|M|H|ND))$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V3"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:3[.][01]/((AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])/)*(AV:[NALP]|AC:[LH]|PR:[NLH]|UI:[NR]|S:[UC]|[CIA]:[NLH]|E:[XUPFH]|RL:[XOTWU]|RC:[XURC]|[CIA]R:[XLMH]|MAV:[XNALP]|MAC:[XLH]|MPR:[XNLH]|MUI:[XNR]|MS:[XUC]|M[CIA]:[XNLH])$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "CVSS_V4"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "pattern": "^CVSS:4[.]0/AV:[NALP]/AC:[LH]/AT:[NP]/PR:[NLH]/UI:[NPA]/VC:[HLN]/VI:[HLN]/VA:[HLN]/SC:[HLN]/SI:[HLN]/SA:[HLN](/E:[XAPU])?(/CR:[XHML])?(/IR:[XHML])?(/AR:[XHML])?(/MAV:[XNALP])?(/MAC:[XLH])?(/MAT:[XNP])?(/MPR:[XNLH])?(/MUI:[XNPA])?(/MVC:[XNLH])?(/MVI:[XNLH])?(/MVA:[XNLH])?(/MSC:[XNLH])?(/MSI:[XNLHS])?(/MSA:[XNLHS])?(/S:[XNP])?(/AU:[XNY])?(/R:[XAUI])?(/V:[XDC])?(/RE:[XLMH])?(/U:(X|Clear|Green|Amber|Red))?$"
                }
              }
            }
          },
          {
            "if": {
              "properties": {
                "type": {
                  "const": "Ubuntu"
                }
              }
            },
            "then": {
              "properties": {
                "score": {
                  "enum": [
                    "negligible",
                    "low",
                    "medium",
                    "high",
                    "critical"
                  ]
                }
              }
            }
          }
        ],
        "required": [
          "type",
          "score"
        ]
      }
    },
    "timestamp": {
      "type": "string",
      "format": "date-time",
      "pattern": "[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}(\\.[0-9]+)?Z"
    }
  },
  "additionalProperties": false
}

=== anchore/grype/grype/db/v6/build/transformers/osv/testdata/UBUNTU-CVE-2001-1593.json
{
  "affected": [
    {
      "ecosystem_specific": {
        "availability": "No subscription required",
        "binaries": [
          {
            "binary_name": "a2ps",
            "binary_version": "1:4.14-1.2"
          }
        ]
      },
      "package": {
        "ecosystem": "Ubuntu:14.04:LTS",
        "name": "a2ps",
        "purl": "pkg:deb/ubuntu/a2ps@1:4.14-1.2?arch=source&distro=trusty"
      },
      "ranges": [
        {
          "database_specific": {
            "anchore": {
              "fixes": [
                {
                  "date": "2014-04-05",
                  "kind": "advisory",
                  "version": "1:4.14-1.2"
                }
              ]
            }
          },
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "1:4.14-1.2"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": [
        "1:4.14-1.1"
      ]
    }
  ],
  "aliases": [],
  "details": "Jakub Wilk found that a2ps, a tool to convert text and other types of files to PostScript, insecurely used a temporary file in spy_user(). A local attacker could use this flaw to perform a symbolic link attack to modify an arbitrary file accessible to the user running a2ps.",
  "id": "UBUNTU-CVE-2001-1593",
  "modified": "2025-07-16T04:49:52Z",
  "published": "2014-04-05T21:55:00Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2001-1593"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2001-1593"
    }
  ],
  "related": [],
  "schema_version": "1.7.0",
  "severity": [
    {
      "score": "low",
      "type": "Ubuntu"
    }
  ],
  "upstream": [
    "CVE-2001-1593"
  ],
  "withdrawn": "2025-07-18T16:42:37Z"
}

=== anchore/grype/grype/db/v6/build/transformers/osv/testdata/ROOT-APP-PYPI-CVE-2025-30473.json
{
  "schema_version": "1.6.1",
  "id": "ROOT-APP-PYPI-CVE-2025-30473",
  "modified": "2024-12-15T14:30:00Z",
  "published": "2024-12-10T09:00:00Z",
  "aliases": [
    "CVE-2025-30473"
  ],
  "summary": "requests vulnerable to improper certificate validation",
  "details": "The requests library before version 2.31.0+root.io.1 contains a vulnerability in certificate validation that may allow man-in-the-middle attacks.",
  "affected": [
    {
      "package": {
        "ecosystem": "Root:PyPI",
        "name": "rootio_requests"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.31.0+root.io.1"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2025-30473"
    }
  ],
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:H/A:N"
    }
  ],
  "database_specific": {
    "source": "Root",
    "anchore": {
      "record_type": "advisory"
    }
  }
}

=== anchore/grype/grype/db/v6/build/transformers/osv/testdata/UBUNTU-CVE-2023-38545.json
{
  "affected": [
    {
      "ecosystem_specific": {
        "availability": "No subscription required",
        "binaries": [
          {
            "binary_name": "curl",
            "binary_version": "7.81.0-1ubuntu1.14"
          },
          {
            "binary_name": "libcurl3-gnutls",
            "binary_version": "7.81.0-1ubuntu1.14"
          },
          {
            "binary_name": "libcurl3-nss",
            "binary_version": "7.81.0-1ubuntu1.14"
          },
          {
            "binary_name": "libcurl4",
            "binary_version": "7.81.0-1ubuntu1.14"
          }
        ],
        "priority_reason": "Upstream curl developer has rated this issue as high"
      },
      "package": {
        "ecosystem": "Ubuntu:22.04:LTS",
        "name": "curl",
        "purl": "pkg:deb/ubuntu/curl@7.81.0-1ubuntu1.14?arch=source&distro=jammy"
      },
      "ranges": [
        {
          "database_specific": {
            "anchore": {
              "fixes": [
                {
                  "date": "2023-10-11",
                  "kind": "advisory",
                  "version": "7.81.0-1ubuntu1.14"
                }
              ]
            }
          },
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "7.81.0-1ubuntu1.14"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": [
        "7.74.0-1.3ubuntu2",
        "7.74.0-1.3ubuntu3",
        "7.80.0-3",
        "7.81.0-1",
        "7.81.0-1ubuntu1.1",
        "7.81.0-1ubuntu1.2",
        "7.81.0-1ubuntu1.3",
        "7.81.0-1ubuntu1.4",
        "7.81.0-1ubuntu1.6",
        "7.81.0-1ubuntu1.7",
        "7.81.0-1ubuntu1.8",
        "7.81.0-1ubuntu1.10",
        "7.81.0-1ubuntu1.11",
        "7.81.0-1ubuntu1.13"
      ]
    },
    {
      "ecosystem_specific": {
        "availability": "No subscription required",
        "binaries": [
          {
            "binary_name": "curl",
            "binary_version": "8.2.1-1ubuntu3.1"
          },
          {
            "binary_name": "libcurl3-gnutls",
            "binary_version": "8.2.1-1ubuntu3.1"
          },
          {
            "binary_name": "libcurl3-nss",
            "binary_version": "8.2.1-1ubuntu3.1"
          },
          {
            "binary_name": "libcurl4",
            "binary_version": "8.2.1-1ubuntu3.1"
          }
        ],
        "priority_reason": "Upstream curl developer has rated this issue as high"
      },
      "package": {
        "ecosystem": "Ubuntu:24.04:LTS",
        "name": "curl",
        "purl": "pkg:deb/ubuntu/curl@8.2.1-1ubuntu3.1?arch=source&distro=noble"
      },
      "ranges": [
        {
          "database_specific": {
            "anchore": {
              "fixes": [
                {
                  "date": "2023-10-11",
                  "kind": "advisory",
                  "version": "8.2.1-1ubuntu3.1"
                }
              ]
            }
          },
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "8.2.1-1ubuntu3.1"
            }
          ],
          "type": "ECOSYSTEM"
        }
      ],
      "versions": [
        "8.2.1-1ubuntu3"
      ]
    }
  ],
  "aliases": [],
  "details": "This flaw makes curl overflow a heap based buffer in the SOCKS5 proxy handshake. When curl is asked to pass along the host name to the SOCKS5 proxy to allow that to resolve the address instead of it getting done by curl itself, the maximum length that host name can be is 255 bytes. If the host name is detected to be longer, curl switches to local name resolving and instead passes on the resolved address only. Due to this bug, the local variable that means \"let the host resolve the name\" could get the wrong value during a slow SOCKS5 handshake, and contrary to the intention, copy the too long host name to the target buffer instead of copying just the resolved address there. The target buffer being a heap based buffer, and the host name coming from the URL that curl has been told to operate with.",
  "id": "UBUNTU-CVE-2023-38545",
  "modified": "2026-04-22T07:45:24Z",
  "published": "2023-10-11T06:00:00Z",
  "references": [
    {
      "type": "REPORT",
      "url": "https://ubuntu.com/security/CVE-2023-38545"
    },
    {
      "type": "REPORT",
      "url": "https://curl.se/docs/CVE-2023-38545.html"
    },
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-6429-1"
    },
    {
      "type": "ADVISORY",
      "url": "https://ubuntu.com/security/notices/USN-6429-3"
    },
    {
      "type": "REPORT",
      "url": "https://www.cve.org/CVERecord?id=CVE-2023-38545"
    }
  ],
  "related": [
    "USN-6429-1",
    "USN-6429-3"
  ],
  "schema_version": "1.7.0",
  "severity": [
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:H/A:H",
      "type": "CVSS_V3"
    },
    {
      "score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H",
      "type": "CVSS_V3"
    },
    {
      "score": "high",
      "type": "Ubuntu"
    }
  ],
  "upstream": [
    "CVE-2023-38545"
  ]
}

=== anchore/grype/grype/db/v6/build/transformers/osv/test-fixtures/ROOT-OS-ALPINE-318-CVE-2000-0548.json
{
  "schema_version": "1.6.1",
  "id": "ROOT-OS-ALPINE-318-CVE-2000-0548",
  "modified": "2024-11-20T16:00:00Z",
  "published": "2024-11-15T12:00:00Z",
  "aliases": [
    "CVE-2000-0548"
  ],
  "summary": "util-linux vulnerability in mount command",
  "details": "The mount command in util-linux before version 2.38.1-r10071 has a vulnerability that could allow local privilege escalation.",
  "affected": [
    {
      "package": {
        "ecosystem": "Alpine:3.18",
        "name": "rootio-util-linux"
      },
      "ranges": [
        {
          "type": "ECOSYSTEM",
          "events": [
            {
              "introduced": "0"
            },
            {
              "fixed": "2.38.1-r10071"
            }
          ]
        }
      ]
    }
  ],
  "references": [
    {
      "type": "ADVISORY",
      "url": "https://nvd.nist.gov/vuln/detail/CVE-2000-0548"
    },
    {
      "type": "WEB",
      "url": "https://security.alpinelinux.org/vuln/CVE-2000-0548"
    }
  ],
  "severity": [
    {
      "type": "CVSS_V3",
      "score": "CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:H/I:H/A:H"
    }
  ],
  "database_specific": {
    "source": "Root",
    "anchore": {
      "record_type": "advisory"
    }
  }
}
